// BlackMagic bridge — auto-generated by BlackMagicReplacer
// .bm files are the source of truth. This file symlinks them to .rs so Cargo
// can compile them. Never edit the .rs files — they are build artifacts.
use std::fs;
use std::os::unix::fs::symlink;
use std::path::Path;

fn main() {
    let src = Path::new("src");
    if !src.exists() { return; }
    for entry in fs::read_dir(src).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("bm") {
            let rs = path.with_extension("rs");
            if !rs.exists() {
                // symlink: main.rs -> main.bm  (relative)
                let bm_name = path.file_name().unwrap();
                let rs_name = rs.file_name().unwrap();
                let _ = symlink(
                    Path::new(bm_name),
                    src.join(rs_name),
                );
            }
        }
    }
    println!("cargo:rerun-if-changed=src");
}
